
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Apr 15 16:11:49 COT 2019
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LLAME = 37;
  public static final int DIVIDE = 9;
  public static final int FUNCTION = 22;
  public static final int MENSAJE = 48;
  public static final int DIFERENTE = 15;
  public static final int RESTA = 7;
  public static final int PARENIZQ = 10;
  public static final int SEMI = 4;
  public static final int REPEAT = 32;
  public static final int LLAVEDER = 20;
  public static final int INT = 49;
  public static final int OUT = 34;
  public static final int FOR = 25;
  public static final int INOUT = 35;
  public static final int AND = 39;
  public static final int MENORIGUAL = 17;
  public static final int CORCHIZQ = 2;
  public static final int IGUAL = 16;
  public static final int OR = 40;
  public static final int IN = 33;
  public static final int BOOL = 51;
  public static final int ENDFOR = 26;
  public static final int NUM = 45;
  public static final int SUMA = 6;
  public static final int ASSIGN = 12;
  public static final int MAIN = 21;
  public static final int IF = 29;
  public static final int ID = 47;
  public static final int ENDWHILE = 28;
  public static final int MAYORIGUAL = 18;
  public static final int DECIMAL = 46;
  public static final int EOF = 0;
  public static final int RETURN = 24;
  public static final int TRUE = 41;
  public static final int error = 1;
  public static final int COMA = 43;
  public static final int MENOR = 13;
  public static final int PARENDER = 11;
  public static final int ESCRIBA = 36;
  public static final int MAYOR = 14;
  public static final int ENDIF = 31;
  public static final int ELSE = 30;
  public static final int CORCHDER = 3;
  public static final int TO = 38;
  public static final int WHILE = 27;
  public static final int LLAVEIZQ = 19;
  public static final int FLOAT = 50;
  public static final int DOSP = 5;
  public static final int MULTI = 8;
  public static final int STRING = 52;
  public static final int FALSE = 42;
  public static final int CERO = 44;
  public static final int PROCEDURE = 23;
}

