/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejecucion;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Highlighter;

/**
 *
 * @author jitzo
 */
public class VistaPrincipal extends javax.swing.JFrame {

    Object[][] data;
    String[] columnNames = {"Variable", "Valor"};
    DefaultTableModel modelo = new DefaultTableModel(data, columnNames);
    Object[][] data2;
    LinkedList<String[]> instrucciones = new LinkedList<>();
    Programa p = new Programa();
    String[] varTable = new String[2];
    LinkedList<Integer> cantidadEjecucion = new LinkedList<>();
    LinkedList<Integer> indiceInicioLinea = new LinkedList<>();
    List<JButton> botones;
    LinkedList<Integer> breakpoints = new LinkedList<>();
    HiloAutomatico h;
    boolean ejecutando = false;
    int cont = 0, contV2 = 0;

    /**
     * Creates new form VistaPrincipal
     *
     * @throws java.io.FileNotFoundException
     */
    public VistaPrincipal() throws FileNotFoundException, IOException {
        initComponents();
        this.setLocationRelativeTo(null);
        LeerAlgoritmo();
        p.main();
        botones = new ArrayList<>();
        this.btnAutomatico.setEnabled(false);
        this.btnPaso.setEnabled(false);
        this.btnejecucion.setEnabled(false);
        this.txtAlgoritmo.setEditable(false);
        this.txtConsola.setEditable(false);
        this.tblSeguimiento.setModel(modelo);
        this.txtConsola.setText("");
        for (String string : p.resultadoConsola) {
            this.txtConsola.append(string + "\n");
        }
        for (String variable : p.variables) {
            String[] var = variable.split("<-");
        }

        int contAux = 0;
        for (int i = 0; i < instrucciones.size(); i++) {
            for (int j = 0; j < p.instrucciones.size(); j++) {
                if (instrucciones.get(i)[0].trim().equals(p.instrucciones.get(j))) {
                    contAux++;
                }
            }
            cantidadEjecucion.add(contAux);
            contAux = 0;
        }
        System.out.println("Variables:\n" + p.variables);
        btnejecucion.setName("pruebaaaa");
    }

    /**
     * Método que lee el algoritmo escrito en el area de texto para seguimiento
     * @throws FileNotFoundException
     * @throws IOException 
     */
    private void LeerAlgoritmo() throws FileNotFoundException, IOException {
        File archivo = new File("src/ejecucion/algoritmo.txt");
        FileReader fr = new FileReader(archivo);
        BufferedReader br = new BufferedReader(fr);
        // Lectura del fichero
        String linea;
        String[] instruccion;
        int pos = 0;
        while ((linea = br.readLine()) != null) {
            instruccion = new String[3];
            instruccion[0] = linea;
            instruccion[1] = String.valueOf(pos);
            instruccion[2] = "0";
            instrucciones.add(instruccion);
            pos += linea.length() + 1;
            this.txtAlgoritmo.append(linea + "\n");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtConsola = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSeguimiento = new javax.swing.JTable();
        btnAutomatico = new javax.swing.JButton();
        btnPaso = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAlgoritmo = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtValores = new javax.swing.JTextArea();
        btnReiniciar = new javax.swing.JButton();
        btnejecucion = new javax.swing.JButton();
        Lienzo = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnMas = new javax.swing.JButton();
        btnMenos = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtConsola.setColumns(20);
        txtConsola.setRows(5);
        jScrollPane1.setViewportView(txtConsola);

        jLabel1.setText("Estado variables");

        jLabel2.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        jLabel2.setText("Entorno de ejecución");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel3.setText("Algoritmo del CareStudent");

        tblSeguimiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblSeguimiento);

        btnAutomatico.setText("Automático");
        btnAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutomaticoActionPerformed(evt);
            }
        });

        btnPaso.setText("Paso a paso");
        btnPaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasoActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        txtAlgoritmo.setColumns(20);
        txtAlgoritmo.setRows(5);
        jScrollPane3.setViewportView(txtAlgoritmo);

        jLabel4.setText("Consola");

        txtValores.setColumns(20);
        txtValores.setRows(5);
        txtValores.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValoresKeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(txtValores);

        btnReiniciar.setText("Reiniciar paso a paso");
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });

        btnejecucion.setText("Pausar");
        btnejecucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnejecucionActionPerformed(evt);
            }
        });

        Lienzo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Lienzo.setLayout(null);

        jLabel5.setText("Puntos");

        jLabel6.setText("Ruptura");

        jLabel7.setText("Cantidad");

        jLabel8.setText("Ejecución");

        btnMas.setText("+");
        btnMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasActionPerformed(evt);
            }
        });

        btnMenos.setText("-");
        btnMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenosActionPerformed(evt);
            }
        });

        jLabel9.setText("Velocidad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(410, 410, 410)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(Lienzo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAutomatico)
                                .addGap(18, 18, 18)
                                .addComponent(btnPaso))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnMas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(btnReiniciar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnejecucion)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel3)
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                        .addGap(91, 91, 91)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(138, 138, 138)))
                .addGap(10, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6))))
                        .addGap(3, 3, 3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lienzo, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnAutomatico)
                                    .addComponent(btnPaso))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnReiniciar)
                                    .addComponent(btnejecucion))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnMas)
                                    .addComponent(btnMenos)
                                    .addComponent(jLabel9)))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * Acción para el botón de ejecución automática
     * @param evt 
     */
    private void btnAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutomaticoActionPerformed
        // TODO add your handling code here:
        this.btnejecucion.setEnabled(true);
        this.btnejecucion.setText("Pausar");
        ejecutando = true;
        modelo.setRowCount(0);
        h = new HiloAutomatico(txtAlgoritmo, txtValores, modelo, instrucciones, p, cantidadEjecucion, indiceInicioLinea, breakpoints, btnejecucion);
        h.start();
    }//GEN-LAST:event_btnAutomaticoActionPerformed

    /**
     * Acción para el botón de ejecución paso a paso
     * @param evt 
     */
    private void btnPasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasoActionPerformed
        // TODO add your handling code here
        String i;
        if (cont < p.instrucciones.size() && (i = p.instrucciones.get(cont)) != null) {
            for (String[] aux : instrucciones) {
                if (aux[0].trim().equals(i)) {
                    SubRayar(Integer.valueOf(aux[1]), aux[0].length());
                    if (aux[0].trim().equals(i)) {
                        SubRayar(Integer.valueOf(aux[1]), aux[0].length());
                        if (aux[0].contains("<-") && contV2 < p.variables.size()) {
                            InsertarTabla(p.variables.get(contV2));
                            contV2++;
                        }
                    }
                }
            }
            cont++;
        }

        // Se termina de leer las lines del programa
        // es decir ya no hay más lineas por ejecutar
        if (cont >= p.instrucciones.size()) {
            ResaltarMalCalculo();
            compararCalculoEstudiante();
            this.btnPaso.setEnabled(false);
        }
    }//GEN-LAST:event_btnPasoActionPerformed

    /**
     * Acción para el botón de reinicio de estado del debug (Automático y Paso a paso)
     * @param evt 
     */
    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        // TODO add your handling code here:
        cont = 0;
        modelo.setRowCount(0);
        contV2 = 0;
        this.btnPaso.setEnabled(true);
        this.btnAutomatico.setEnabled(true);
        this.txtAlgoritmo.getHighlighter().removeAllHighlights();
        this.txtValores.getHighlighter().removeAllHighlights();
    }//GEN-LAST:event_btnReiniciarActionPerformed

    /**
     * Evento para el campo de edición de los valores
     * de ejecución ingresador por el usuario
     * @param evt 
     */
    private void txtValoresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValoresKeyReleased
        // TODO add your handling code here:
        if (instrucciones.size() == txtValores.getText().split("\n").length) {
            this.btnAutomatico.setEnabled(true);
            this.btnPaso.setEnabled(true);
        } else {
            this.btnAutomatico.setEnabled(false);
            this.btnPaso.setEnabled(false);
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int n = this.txtValores.getText().split("\n").length;
            botones.clear();
            Lienzo.removeAll();
            int posY = 5;
            int tamano;
            for (int i = 1; i <= n + 1; i++) {
                tamano = 15;
                agregarBoton(i, posY, tamano);
                posY = posY + tamano;
            }
        }
        if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
            int n = this.txtValores.getText().split("\n").length;
            botones.clear();
            Lienzo.removeAll();
            int posY = 5;
            int tamano;
            for (int i = 1; i <= n + 1; i++) {
                tamano = 15;
                agregarBoton(i, posY, tamano);
                posY = posY + tamano;
            }
        }
    }//GEN-LAST:event_txtValoresKeyReleased

    /**
     * Acción para el botón que Pausa o Reanuda la ejecuión del debug Automático
     * @param evt 
     */
    private void btnejecucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnejecucionActionPerformed
        System.out.println("Ejecutando: "+ejecutando);
        if (this.btnejecucion.getText().equals("Reanudar")) {
            h.ejecutar = true;
            ejecutando = true;
            this.btnejecucion.setText("Pausar");
        }else{
            if (ejecutando) {
                h.ejecutar = false;
                ejecutando = false;
                this.btnejecucion.setText("Reanudar");
            } else {
                h.ejecutar = true;
                ejecutando = true;
                this.btnejecucion.setText("Pausar");
            }
        }
        
    }//GEN-LAST:event_btnejecucionActionPerformed

    /**
     * Acción para el botón que disminuye la velocidad de ejecución del debug
     * @param evt 
     */
    private void btnMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenosActionPerformed
        // TODO add your handling code here:
        h.velocidad+=50;
    }//GEN-LAST:event_btnMenosActionPerformed

    /**
     * Acción para el botón que aumenta la velocidad de ejecución del debug
     * @param evt 
     */
    private void btnMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasActionPerformed
        // TODO add your handling code here:
        h.velocidad-=50;
    }//GEN-LAST:event_btnMasActionPerformed

    /**
     * Agrega los botones de breakpoint para la ejecución del debug
     * @param i
     * @param posy
     * @param tamano 
     */
    private void agregarBoton(int i, int posy, int tamano) {
        JButton boton = new JButton();
        boton.setName("" + (i - 1));
        boton.setBounds(0, posy, tamano, tamano);
        boton.addMouseListener(new MouseListener() {
            boolean b = true;

            @Override
            public void mouseClicked(MouseEvent e) {
                if (b) {
                    boton.setBackground(Color.red);
                    breakpoints.add(Integer.valueOf(boton.getName()));
                    b = false;
                } else {
                    boton.setBackground(Color.lightGray);
                    breakpoints.remove(Integer.valueOf(boton.getName()));
                    b = true;
                }
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        });
        botones.add(boton);
        Lienzo.add(boton);
        Lienzo.updateUI();
    }

    /**
     * Método que muestra el estado de las variables en la tabla de seguimiento
     * @param s 
     */
    private void InsertarTabla(String s) {
        String[] aux = s.split("<-");
        String[] row = {aux[0], aux[1]};
        boolean b = false;
        int rows = modelo.getRowCount();
        for (int i = 0; i < rows; i++) {
            String var = String.valueOf(modelo.getValueAt(i, 0));
            if (var.equals(aux[0])) {
                modelo.setValueAt(aux[1], i, 1);
                b = true;
                break;
            }
        }
        if (!b) {
            this.modelo.addRow(row);
        }
    }

    /**
     * Método que detecta los valores de ejecución ingresados por el usuario,
     * que no concuerdan con los valores reales calculados por la aplicación
     */
    private void ResaltarMalCalculo() {
        String split[] = this.txtValores.getText().split("\n");
        String area = this.txtValores.getText();
        indiceInicioLinea.add(1);
        for (int i = 1; i < area.length(); i++) {
            if (area.charAt(i) == '\n') {
                indiceInicioLinea.add(i + 1);
            }
        }
    }

    /**
     * Método que resalta la linea que se está ejecutando actualmente
     * @param pos
     * @param fin 
     */
    private void SubRayar(int pos, int fin) {
        Highlighter h = this.txtAlgoritmo.getHighlighter();
        h.removeAllHighlights();
        try {
            h.addHighlight(pos, pos + fin, new DefaultHighlighter.DefaultHighlightPainter(Color.CYAN));
        } catch (BadLocationException e) {
        }
    }

    /**
     * Método que resalta los valores de ejecución ingresados por el usuario,
     * que no concuerdan con los valores reales calculados por la aplicación
     * @param pos
     * @param fin 
     */
    private void SubRayar2(int pos, int fin) {
        Highlighter h = this.txtValores.getHighlighter();
        try {
            h.addHighlight(pos, pos + fin, new DefaultHighlighter.DefaultHighlightPainter(Color.RED));
        } catch (BadLocationException e) {
        }
    }

    /**
     * Método que compara los valores de ejecución ingresados por el usuario,
     * con los valores reales calculados por la aplicación
     */
    private void compararCalculoEstudiante() {
        String[] valores = this.txtValores.getText().split("\n");
        int sumaV = 0;
        for (int i = 0; i < valores.length; i++) {
            int valor = Integer.valueOf(valores[i]);
          
            if (valor != cantidadEjecucion.get(i)) {
                SubRayar2(indiceInicioLinea.get(i), valores[i].length());
            }else{
                  sumaV += valor;
            }
        }
        int sumaC = 0;
        for (Integer integer : cantidadEjecucion) {
            sumaC += integer;
        }
        int x = (sumaV*100)/sumaC;
        JOptionPane.showMessageDialog(this, "Cantidad  real de ejecución: "+sumaC+"\nCantidad de ejecución ingresada: "+sumaV+"\nAcertó en un "+x+"%");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VistaPrincipal().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(VistaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(VistaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Lienzo;
    private javax.swing.JButton btnAutomatico;
    private javax.swing.JButton btnMas;
    private javax.swing.JButton btnMenos;
    private javax.swing.JButton btnPaso;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton btnejecucion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tblSeguimiento;
    private javax.swing.JTextArea txtAlgoritmo;
    private javax.swing.JTextArea txtConsola;
    private javax.swing.JTextArea txtValores;
    // End of variables declaration//GEN-END:variables
}
