
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Mar 05 21:59:51 COT 2019
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 35;
  public static final int DIVIDE = 9;
  public static final int FUNCTION = 21;
  public static final int DIFERENTE = 15;
  public static final int RESTA = 7;
  public static final int PARENIZQ = 10;
  public static final int SEMI = 5;
  public static final int REPEAT = 30;
  public static final int LLAVEDER = 19;
  public static final int INT = 32;
  public static final int FOR = 24;
  public static final int CORCHIZQ = 2;
  public static final int IGUAL = 16;
  public static final int ENDFOR = 25;
  public static final int SUMA = 6;
  public static final int ASSIGN = 12;
  public static final int MAIN = 20;
  public static final int IF = 28;
  public static final int ID = 36;
  public static final int ENDWHILE = 27;
  public static final int EOF = 0;
  public static final int BOOLEAN = 34;
  public static final int RETURN = 23;
  public static final int error = 1;
  public static final int COMILLA = 17;
  public static final int MENOR = 13;
  public static final int PARENDER = 11;
  public static final int MAYOR = 14;
  public static final int ENDIF = 29;
  public static final int PUNTO = 4;
  public static final int CORCHDER = 3;
  public static final int WHILE = 26;
  public static final int LLAVEIZQ = 18;
  public static final int FLOAT = 33;
  public static final int MULTI = 8;
  public static final int ENDREPEAT = 31;
  public static final int PROCEDURE = 22;
}

